spring.application.name=Task

spring.datasource.url=jdbc:postgresql://localhost:5432/university
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false